export const CMD = {
  START: /^\/(start|시작|메뉴)$/i,
  HELP: /^\/(help|도움말)$/i,
  BRIEF: /^\/(brief|morning|브리핑|장전)$/i,
  WEEKLY_COPILOT: /^\/(weekly|weeklycopilot|주간코파일럿)(?:\s+(.+))?$/i,
  REPORT: /^\/(report|리포트)(?:\s+(.+))?$/i,
  GUIDEPDF: /^\/(guidepdf|가이드pdf|운영가이드pdf)$/i,
  TRADE: /^\/(analyze|종목분석)\s+(.+)$/i,
  SECTOR: /^\/(sector|섹터|업종|테마)$/i,
  STOCKS: /^\/(stocks|종목)\s+(.+)$/i,
  PULLBACK: /^\/(pullback|눌림목)$/i,
  ECONOMY: /^\/(economy|경제)$/i,
  MARKET: /^\/(market|시장)$/i,
  ONBOARDING: /^\/(onboarding|온보딩|시작하기|가이드)$/i,
  SCAN: /^\/(scan|스캔)(?:\s+(.+))?$/i,
  NEWS: /^\/(news|뉴스)(?:\s+(.+))?$/i,
  FLOW: /^\/(flow|수급)(?:\s+(.+))?$/i,
  FINANCE: /^\/(finance|재무)(?:\s+(.+))?$/i,
  CAPITAL: /^\/(capital|투자금)(?:\s+(.+))?$/i,
  AUTOTRUST: /^\/(신뢰도|autotrust)(?:\s+(.+))?$/i,
  AUTOSHADOW: /^\/(섀도우|shadow)(?:\s+(.+))?$/i,
  AUTOBACKTEST: /^\/(자동백테스트|autobacktest)(?:\s+(.+))?$/i,
  RISK_PROFILE: /^\/(투자성향|성향|risk|riskprofile)(?:\s+(.+))?$/i,
  WATCHONLYLIST: /^\/(watchlist|관심)$/i,
  WATCHONLYADD: /^\/(watchadd|관심추가)(?:\s+(.+))?$/i,
  WATCHONLYREMOVE: /^\/(watchremove|관심제거)(?:\s+(.+))?$/i,
  WATCHONLYRESET: /^\/(watchreset|관심초기화)(?:\s+(.+))?$/i,
  WATCHONLYRESP: /^\/(watchplan|관심대응)$/i,
  WATCHADD: /^\/(paperbuy|가상매수)(?:\s+(.+))?$/i,
  WATCHREMOVE: /^\/(papersell|가상매도)(?:\s+(.+))?$/i,
  WATCHEDIT: /^\/(holdingedit|보유수정)(?:\s+(.+))?$/i,
  WATCHRESTORE: /^\/(holdingrestore|보유복구)(?:\s+(.+))?$/i,
  WATCHAUTO: /^\/(autosellcheck|자동매도점검)$/i,
  WATCHRESP: /^\/(holdingplan|보유대응|관심대응)$/i,
  RECORD: /^\/(tradelog|거래기록)(?:\s+(.+))?$/i,
  LIQUIDATEALL: /^\/(liquidateall|전체매도)(?:\s+(.+))?$/i,
  ALERT: /^\/(alert|이상징후|알림)$/i,
  WATCHLIST: /^\/(holdings|보유)$/i,
  AUTOCYCLE: /^\/(autocycle|자동사이클)(?:\s+(.+))?$/i,
  PREMARKET: /^\/(premarket|장전플랜|직장인플랜|오늘주문)(?:\s+(.+))?$/i,
  RANKING: /^\/(ranking|랭킹|순위)$/i,
  PROFILE: /^\/(profile|프로필|내정보)$/i,
  FOLLOW: /^\/(follow|팔로우)(?:\s+(.+))?$/i,
  UNFOLLOW: /^\/(unfollow|언팔로우)(?:\s+(.+))?$/i,
  FEED: /^\/(feed|피드)$/i,
  NEXTSECTOR: /^\/(nextsector|다음섹터|수급섹터)$/i,
  KOSPI: /^(?:\/)?(kospi|코스피)$/i,
  KOSDAQ: /^(?:\/)?(kosdaq|코스닥)$/i,
  ETF: /^(?:\/)?(etf|이티에프)(?:\s+(.+))?$/i,
  ETFHUB: /^(?:\/)?(etfhub|이티에프허브|etf허브)(?:\s+(.+))?$/i,
  ETFCORE: /^\/(etfcore)(?:\s+(.+))?$/i,
  ETFTHEME: /^\/(etftheme)(?:\s+(.+))?$/i,
  ETFINFO: /^\/(etfinfo)(?:\s+(.+))?$/i,
  ETFDIV: /^\/(etfdiv)(?:\s+(.+))?$/i,
  STRATEGY_SELECT: /^\/(전략선택|strategy)$/i,
};

export function normalizeIncomingMessageText(text: string): string {
  return (text || "")
    .trim()
    .replace(/^\/([^@\s]+)@[^\s]+(?=\s|$)/, "/$1");
}
